// generated by zed-pkg-test/test-org-fleet
import assert from 'node:assert/strict';
import childProcess from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { readFleetManifest } from '../scripts/read-fleet-manifest.mjs';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const manifestPath = path.join(root, 'bootstrap', 'test-org-fleet.json.gz');
const manifest = readFleetManifest(manifestPath);

test('fleet contains the intended organization pairs and never r2g', () => {
  assert.equal(manifest.pairs.length, 18);
  const names = new Set(manifest.pairs.flatMap((pair) => [pair.sourceOrg.toLowerCase(), pair.testOrg.toLowerCase()]));
  assert.equal(names.has('r2g'), false);
  assert.equal(names.has('r2g-test'), false);
  for (const pair of manifest.pairs) assert.match(pair.testOrg, /-test$/i);
});

test('repository names are unique inside every test org', () => {
  for (const pair of manifest.pairs) {
    const names = [...(pair.existingRepositories ?? []), ...pair.repositories.map((repository) => repository.name)];
    assert.equal(new Set(names).size, names.length, pair.testOrg);
  }
});

test('fiducia has exactly ten three-lane language consumers', () => {
  const pair = manifest.pairs.find((candidate) => candidate.testOrg === 'fiducia-cloud-test');
  const clients = pair.repositories.filter((repository) => /^fiducia-.+-client-e2e$/.test(repository.name));
  assert.equal(clients.length, 10);
  for (const repository of clients) {
    const modes = new Set(repository.imports.map((dependency) => dependency.mode));
    assert.deepEqual([...['git-submodule', 'zed', 'native-package'].filter((mode) => !modes.has(mode))], []);
  }
});

test('validator succeeds and reports the complete fleet', () => {
  const result = childProcess.spawnSync(process.execPath, [path.join(root, 'scripts', 'validate-test-org-fleet.mjs'), '--json'], { cwd: root, encoding: 'utf8' });
  assert.equal(result.status, 0, result.stderr);
  const summary = JSON.parse(result.stdout);
  assert.equal(summary.pairs, 18);
  assert.equal(summary.createRepositories, 301);
  assert.equal(summary.governanceRepositories, 18);
  assert.equal(summary.existingRepositories, 22);
  assert.equal(summary.errors, 0);
});

test('bootstrap dry run is deterministic and write-free', () => {
  const result = childProcess.spawnSync(process.execPath, [path.join(root, 'scripts', 'bootstrap-test-org-fleet.mjs'), '--dry-run', '--summary-json'], { cwd: root, encoding: 'utf8', env: { ...process.env, GH_TOKEN: '', GITHUB_TOKEN: '' } });
  assert.equal(result.status, 0, result.stderr);
  const summary = JSON.parse(result.stdout);
  assert.equal(summary.mode, 'dry-run');
  assert.equal(summary.selectedOrganizations, 18);
  assert.equal(summary.selectedRepositories, 301);
  assert.equal(summary.governanceRepositories, 18);
  assert.equal(summary.planned, 319);
  assert.equal(summary.created, 0);
  assert.equal(summary.committed, 0);
  assert.equal(summary.pullRequests, 0);
});
