// generated by zed-pkg-test/test-org-fleet
import assert from 'node:assert/strict';
import childProcess from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { readFleetManifest } from '../scripts/read-fleet-manifest.mjs';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const manifestPath = path.join(root, 'bootstrap', 'test-org-fleet.json.gz');
const manifest = readFleetManifest(manifestPath);
const credentialLiteral = /(?:ghp_|github_pat_)[A-Za-z0-9_]{20,}/;
const interruptedOrganizations = [
  'evento-globolo-test',
  'fiducia-cloud-test',
  'sonus-auris-test',
  'messaging-intel-test',
  'quaestor-ledger-test',
  'opto-sync-test',
  'memebank-test',
  'file-tunnel-test',
  'scintilla-run-test',
  'streempilot-test',
  'shared-auth-test',
  'hypesiege-test',
];

test('fleet contains the intended organization pairs and never r2g', () => {
  assert.equal(manifest.pairs.length, 18);
  const names = new Set(manifest.pairs.flatMap((pair) => [pair.sourceOrg.toLowerCase(), pair.testOrg.toLowerCase()]));
  assert.equal(names.has('r2g'), false);
  assert.equal(names.has('r2g-test'), false);
  for (const pair of manifest.pairs) assert.match(pair.testOrg, /-test$/i);
});

test('repository names are unique inside every test org', () => {
  for (const pair of manifest.pairs) {
    const names = [...(pair.existingRepositories ?? []), ...pair.repositories.map((repository) => repository.name)];
    assert.equal(new Set(names).size, names.length, pair.testOrg);
  }
});

test('fiducia has exactly ten three-lane language consumers', () => {
  const pair = manifest.pairs.find((candidate) => candidate.testOrg === 'fiducia-cloud-test');
  const clients = pair.repositories.filter((repository) => /^fiducia-.+-client-e2e$/.test(repository.name));
  assert.equal(clients.length, 10);
  for (const repository of clients) {
    const modes = new Set(repository.imports.map((dependency) => dependency.mode));
    assert.deepEqual([...['git-submodule', 'zed', 'native-package'].filter((mode) => !modes.has(mode))], []);
  }
});

test('validator succeeds and reports the complete fleet', () => {
  const result = childProcess.spawnSync(process.execPath, [path.join(root, 'scripts', 'validate-test-org-fleet.mjs'), '--json'], { cwd: root, encoding: 'utf8' });
  assert.equal(result.status, 0, result.stderr);
  const summary = JSON.parse(result.stdout);
  assert.equal(summary.pairs, 18);
  assert.equal(summary.createRepositories, 301);
  assert.equal(summary.governanceRepositories, 18);
  assert.equal(summary.existingRepositories, 22);
  assert.equal(summary.errors, 0);
});

test('bootstrap dry run is deterministic and write-free', () => {
  const result = childProcess.spawnSync(process.execPath, [path.join(root, 'scripts', 'bootstrap-test-org-fleet.mjs'), '--dry-run', '--summary-json'], { cwd: root, encoding: 'utf8', env: { ...process.env, GH_TOKEN: '', GITHUB_TOKEN: '' } });
  assert.equal(result.status, 0, result.stderr);
  const summary = JSON.parse(result.stdout);
  assert.equal(summary.mode, 'dry-run');
  assert.equal(summary.selectedOrganizations, 18);
  assert.equal(summary.selectedRepositories, 301);
  assert.equal(summary.governanceRepositories, 18);
  assert.equal(summary.planned, 319);
  assert.equal(summary.created, 0);
  assert.equal(summary.committed, 0);
  assert.equal(summary.pullRequests, 0);
});

test('secret-backed apply workflow covers every test organization and never embeds a credential', () => {
  const workflowPath = path.join(root, '.github', 'workflows', 'apply-test-org-fleet.yml');
  const documentationPath = path.join(root, 'docs', 'test-org-fleet-app-auth.md');
  const workflow = fs.readFileSync(workflowPath, 'utf8');
  const documentation = fs.readFileSync(documentationPath, 'utf8');

  for (const pair of manifest.pairs) {
    assert.equal(workflow.includes(`- ${pair.testOrg}`), true, `missing ${pair.testOrg}`);
  }

  assert.equal(workflow.toLowerCase().includes('r2g-test'), false);
  assert.match(workflow, /actions\/create-github-app-token@[0-9a-f]{40}/);
  assert.match(workflow, /permission-administration: write/);
  assert.match(workflow, /permission-contents: write/);
  assert.match(workflow, /permission-metadata: read/);
  assert.match(workflow, /permission-pull-requests: write/);
  assert.match(workflow, /permission-workflows: write/);
  assert.match(workflow, /secrets\.FLEET_GH_TOKEN/);
  assert.match(workflow, /authentication:\n[\s\S]*?- auto\n[\s\S]*?- pat\n[\s\S]*?- github-app/);
  assert.match(workflow, /APPLY_TEST_FLEET/);
  assert.match(workflow, /GH_TOKEN=%s/);
  assert.match(documentation, /Actions secret `FLEET_GH_TOKEN`/);

  assert.equal(credentialLiteral.test(workflow), false);
  assert.equal(credentialLiteral.test(documentation), false);
  assert.doesNotMatch(workflow, /^\s+(?:token|pat):\s*$/m);
});

test('fleet apply serializes organizations and retries GitHub secondary content limits', () => {
  const workflowPath = path.join(root, '.github', 'workflows', 'apply-test-org-fleet.yml');
  const launcherPath = path.join(root, 'scripts', 'bootstrap-test-org-fleet.mjs');
  const workflow = fs.readFileSync(workflowPath, 'utf8');
  const launcher = fs.readFileSync(launcherPath, 'utf8');

  assert.match(workflow, /timeout-minutes: 90/);
  assert.match(workflow, /max-parallel: 1/);
  assert.match(launcher, /attempt < 14/);
  assert.match(launcher, /secondary rate limit\|temporarily blocked from content creation\|abuse detection/);
  assert.match(launcher, /x-ratelimit-reset/);
  assert.match(launcher, /Math\.min\(180000, 15000 \* \(2 \*\* attempt\)\)/);
  assert.match(launcher, /retrying GitHub API request after rate limit/);
});

test('generated harness branches use authenticated git transport without staging the askpass helper', () => {
  const launcherPath = path.join(root, 'scripts', 'bootstrap-test-org-fleet.mjs');
  const launcher = fs.readFileSync(launcherPath, 'utf8');

  assert.match(launcher, /spawnSync\('git'/);
  assert.match(launcher, /GIT_ASKPASS_REQUIRE: 'force'/);
  assert.match(launcher, /const askpassDirectory = fs\.mkdtempSync\(path\.join\(os\.tmpdir\(\), 'test-org-fleet-askpass-'\)\)/);
  assert.match(launcher, /const askpass = path\.join\(askpassDirectory, 'git-askpass\.sh'\)/);
  assert.doesNotMatch(launcher, /const askpass = path\.join\(worktree, 'git-askpass\.sh'\)/);
  assert.match(launcher, /fs\.rmSync\(askpassDirectory, \{ recursive: true, force: true \}\)/);
  assert.match(launcher, /\['push', '--quiet', 'origin'/);
  assert.match(launcher, /update-index/);
  assert.match(launcher, /--cacheinfo/);
  assert.match(launcher, /TEST_ORG_FLEET_SKIP_TOPICS/);
  assert.match(launcher, /pushed generated commit with git transport/);
  assert.equal(credentialLiteral.test(launcher), false);
});

test('one-time recovery resumes exactly the interrupted organizations in serial', () => {
  const workflowPath = path.join(root, '.github', 'workflows', 'resume-test-org-fleet.yml');
  const workflow = fs.readFileSync(workflowPath, 'utf8');
  const listedOrganizations = [...workflow.matchAll(/^\s+- ([a-z0-9-]+-test)$/gm)].map((match) => match[1]);

  assert.deepEqual(listedOrganizations, interruptedOrganizations);
  assert.equal(workflow.toLowerCase().includes('r2g-test'), false);
  assert.equal(credentialLiteral.test(workflow), false);
  assert.match(workflow, /push:\n\s+branches: \[main\]/);
  assert.match(workflow, /timeout-minutes: 120/);
  assert.match(workflow, /max-parallel: 1/);
  assert.match(workflow, /secrets\.FLEET_GH_TOKEN/);
  assert.match(workflow, /TEST_ORG_FLEET_SKIP_TOPICS: "true"/);
  assert.match(workflow, /--apply/);
  assert.match(workflow, /--concurrency 1/);
  assert.doesNotMatch(workflow, /workflow_dispatch:/);
});

test('one-time handoff persists only ciphertext and dispatches the secret-backed fleet workflow', () => {
  const workflowPath = path.join(root, '.github', 'workflows', 'secure-fleet-token-handoff.yml');
  const workflow = fs.readFileSync(workflowPath, 'utf8');

  for (const pair of manifest.pairs) {
    assert.equal(workflow.includes(`            ${pair.testOrg}`), true, `handoff missing ${pair.testOrg}`);
  }

  assert.equal(workflow.toLowerCase().includes('r2g-test'), false);
  assert.equal(credentialLiteral.test(workflow), false);
  assert.match(workflow, /permissions:\n  contents: write/);
  assert.match(workflow, /RSA-OAEP-SHA256/);
  assert.match(workflow, /openssl pkeyutl -decrypt/);
  assert.match(workflow, /ciphertext\.b64/);
  assert.match(workflow, /EXPECTED_LOGIN: ORESoftware/);
  assert.match(workflow, /gh secret set FLEET_GH_TOKEN/);
  assert.match(workflow, /gh workflow run apply-test-org-fleet\.yml/);
  assert.match(workflow, /-f authentication=pat/);
  assert.match(workflow, /-f confirm=APPLY_TEST_FLEET/);
  assert.match(workflow, /github\.repository == 'zed-pkg-test\/zed-pkg-e2e'/);
  assert.doesNotMatch(workflow, /workflow_dispatch:/);
});
